version: "3.9"
services:
  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mcp-server
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.env
    depends_on:
      - opensearch

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
