version: "3.9"
services:
  wazuh-manager:
    image: wazuh/wazuh:4.6.0
    container_name: wazuh-manager
    ports:
      - "1514:1514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=http://opensearch:9200
    depends_on:
      - opensearch

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"

  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mcp-server
    ports:
      - "8000:8000"
    depends_on:
      - wazuh-manager
      - opensearch
